version: '3'
services:
  server:
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - mongo
    ports:
      - "8000:8000"
      
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client-react
    ports:
      - "8082:8082"

  mongo:
    image: mongo
    restart: always
    ports: 
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo
