export enum ActionType {
  LOGINUSER = "LOGINUSER",
  LOGOUTUSER = "LOGOUTUSER",

  SIGNINUSER = "SIGNINUSER",
  ACTIVEUSERACCOUNT = "ACTIVEUSERACCOUNT",

  PASSWORDRESET = "PASSWORDRESET",
  PASSWORDRESETCONFIRM = "PASSWORDRESETCONFIRM"
}